"""
Site-wide audit — runs the universal page audit on every HTML page.

Also re-runs the article-specific audit (audit_article.py soft mode, imported
as a module) on every file under articles/ and every root-level article-*.html.

Usage:
    python audit_site.py                     # audit the whole site
    python audit_site.py --strict            # same + article strict mode where applicable
    python audit_site.py --only-articles     # skip homepage, locations, etc.
    python audit_site.py --only-universal    # only universal checks, skip article-specific

Exit 0 if every page passes. Exit 1 if any page has a failure.
Writes SITE_AUDIT.md with a human-readable summary.
"""

import subprocess
import sys
from pathlib import Path

from audit_page import audit_page_universal, audit_css_regression_site, read


def is_article(path: Path) -> bool:
    """Article pages are in articles/ or match article-*.html at the root."""
    name = path.name
    parent = path.parent.name
    if parent == "articles" and name.endswith(".html"):
        return True
    if path.parent == Path(".") and name.startswith("article-") and name.endswith(".html"):
        return True
    return False


def find_html_pages(root: Path):
    """Returns a sorted list of every HTML page we want to audit.

    Includes: root-level pages (index, about, contact, costs, safety, etc.),
    articles/, locations/ (city + state hubs). Excludes: 404.html, _dist/,
    _drafts/, deploy */ snapshots, node_modules/ etc.
    """
    skip_dirs = {"_dist", "_drafts", "node_modules", ".git", ".agents", "docs"}
    skip_prefixes = ("deploy ",)
    skip_files = {"404.html"}
    pages = []
    for p in root.rglob("*.html"):
        # skip any path containing a skip-dir segment
        if any(part in skip_dirs for part in p.parts):
            continue
        if any(p.parts and p.parts[0].startswith(prefix) for prefix in skip_prefixes):
            continue
        if p.name in skip_files:
            continue
        # Convention: underscore-prefixed HTML files are dev previews / partials,
        # not production pages (e.g. images/_preview.html). Skip the audit.
        if p.name.startswith("_"):
            continue
        pages.append(p)
    return sorted(pages)


def run_article_audit(path: Path, strict: bool) -> int:
    """Runs audit_article.py as a subprocess and returns its exit code."""
    cmd = [sys.executable, "audit_article.py", str(path)]
    if strict:
        cmd.extend(["--strict", "--browser-verified"])
    result = subprocess.run(cmd, capture_output=True, text=True)
    # Only print if failed to keep the site-wide output readable
    if result.returncode != 0:
        print(result.stdout[-2000:])  # last 2000 chars of output
        if result.stderr:
            print("STDERR:", result.stderr[:500])
    return result.returncode


def main():
    args = sys.argv[1:]
    strict = "--strict" in args
    only_articles = "--only-articles" in args
    only_universal = "--only-universal" in args

    root = Path(".")
    pages = find_html_pages(root)

    if only_articles:
        pages = [p for p in pages if is_article(p)]

    print(f"Site audit — {len(pages)} HTML page(s)")
    print("=" * 70)

    total_fails = 0
    page_fails = 0
    article_fails = 0
    failing_pages = []

    # Site-wide CSS regression check (runs once, not per-page)
    css_fails = audit_css_regression_site()
    total_fails += css_fails

    for p in pages:
        html = read(str(p))
        universal_fails = audit_page_universal(html, str(p))
        if universal_fails > 0:
            page_fails += 1
            failing_pages.append((str(p), f"{universal_fails} universal"))
        total_fails += universal_fails

        if not only_universal and is_article(p):
            art_code = run_article_audit(p, strict)
            if art_code != 0:
                article_fails += 1
                failing_pages.append((str(p), "article-specific"))
                total_fails += 1

    # Summary
    print()
    print("=" * 70)
    print(f"SITE AUDIT SUMMARY")
    print(f"  Pages audited:       {len(pages)}")
    print(f"  Pages with failures: {page_fails}")
    print(f"  Article-specific failures: {article_fails}")
    print(f"  CSS regression fails: {css_fails}")
    print(f"  Total failure count: {total_fails}")

    if failing_pages:
        print("\nFAILING PAGES:")
        for path, reason in failing_pages:
            print(f"  - {path}  ({reason})")

    # Write SITE_AUDIT.md
    summary_md = f"""# Site Audit Summary

_Generated by `python audit_site.py{' --strict' if strict else ''}`._

- **Pages audited:** {len(pages)}
- **Pages with failures:** {page_fails}
- **Article-specific failures:** {article_fails}
- **CSS regression fails:** {css_fails}
- **Total failure count:** {total_fails}

## Failing pages
"""
    if failing_pages:
        for path, reason in failing_pages:
            summary_md += f"- `{path}` — {reason}\n"
    else:
        summary_md += "_None — site is clean._\n"

    Path("SITE_AUDIT.md").write_text(summary_md, encoding="utf-8")
    print("\nReport written to SITE_AUDIT.md")

    if total_fails == 0:
        print("\nOK — whole site clean.")
        sys.exit(0)
    else:
        print(f"\nFAIL — fix the pages above.")
        sys.exit(1)


if __name__ == "__main__":
    main()
