"""
Generate article-card grids on /articles and /author-gyanesh from cluster_map.json.

Replaces hand-maintenance of two article-card grids that were drifting:
  - articles.html: <div class="articles-list-grid" id="articlesGrid"> ... cards ...
  - author-gyanesh.html: <div class="articles-grid"> ... cards ...

Source of truth (priority):
  1. cluster_map.json -- article list, slug, path, title, date_published,
     card_description, status (live only included)
  2. Each article's HTML file -- hero image src + alt, tag class + label
     (so cards inherit the same visuals the article itself uses)

Auto-invoked from:
  - build.sh (Cloudflare Pages deploy-time backstop -- Layer 1)
  - scripts/pre-commit (commit-time sync -- Layer 2, when HTML A/D/R in
    articles/ or root article-*.html, OR cluster_map.json modified)

Modes:
  --generate (default): read cluster_map.json + article HTML, write grids
  --migrate: backfill card_description into cluster_map.json from the
             current articles.html cards (one-time, before sentinels are
             added). Idempotent.

Author-page cards prepend "Cn cluster -- " to the description (where Cn is
the cluster short id like "C3"). Pillars get "Cn pillar -- " instead.
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
CLUSTER_MAP = ROOT / "cluster_map.json"
ARTICLES_HTML = ROOT / "articles.html"
AUTHOR_HTML = ROOT / "author-gyanesh.html"

ARTICLES_SENTINEL_START = "<!-- AUTO-GENERATED ARTICLE GRID START -- regenerated by scripts/generate_article_grids.py from cluster_map.json -->"
ARTICLES_SENTINEL_END = "<!-- AUTO-GENERATED ARTICLE GRID END -->"

MONTHS = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]

# Maps article-tag CSS class -> data-category filter value used in articles.html
TAG_TO_CATEGORY = {
    "tag-guide": "guide",
    "tag-safety": "safety",
    "tag-emergency": "emergency",
    "tag-cost": "cost",
    "tag-maintenance": "maintenance",
    "tag-seasonal": "seasonal",
}


def load_cluster_map():
    with CLUSTER_MAP.open(encoding="utf-8") as f:
        return json.load(f)


def save_cluster_map(data):
    with CLUSTER_MAP.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")


def cluster_short_id(cluster_id: str) -> str:
    """C3_heatpump -> C3"""
    return cluster_id.split("_")[0]


def collect_articles(cmap):
    """Return list of live article dicts: cluster_id, slug, path, title, date_published, card_description, is_pillar.

    Sort: newest date first, then most recently added (within cluster_map.json's articles[] array)
    first as a same-date tiebreak. cluster_map.json is append-only on article ship -- the last
    entry in a cluster's articles[] is the most recently shipped article -- so the array index
    is a reliable proxy for ship order when multiple articles share a date. Slug is the final
    tiebreak for total stability (and only fires when two articles share BOTH date and array
    index, which is essentially never).
    """
    articles = []
    insertion_index = 0  # monotonic across all clusters, captures insertion order
    for cid, c in cmap["clusters"].items():
        p = c.get("pillar", {})
        if p.get("status") == "live":
            articles.append({
                "cluster_id": cid,
                "slug": p["slug"],
                "path": p["filename"],
                "title": p["title"],
                "date_published": p.get("date_published", "2026-04-01"),
                "card_description": p.get("card_description", ""),
                "is_pillar": True,
                "_insertion_index": insertion_index,
            })
            insertion_index += 1
        for a in c.get("articles", []):
            if a.get("status") == "live":
                articles.append({
                    "cluster_id": cid,
                    "slug": a["slug"],
                    "path": a["path"],
                    "title": a["title"],
                    "date_published": a.get("date_published", "2026-04-01"),
                    "card_description": a.get("card_description", ""),
                    "is_pillar": False,
                    "_insertion_index": insertion_index,
                })
                insertion_index += 1
    # Sort: newest date first; on same-date ties, newer insertion (higher index) first; then slug.
    articles.sort(key=lambda a: (a["date_published"], a["_insertion_index"], a["slug"]), reverse=True)
    return articles


def parse_article_meta(html_path: Path):
    """Extract hero image src, alt, tag class, tag label from an article's HTML."""
    if not html_path.exists():
        return {"img_src": "", "img_alt": "", "tag_class": "tag-guide", "tag_label": "&#128218; Guide"}
    html = html_path.read_text(encoding="utf-8")

    # Hero image: class="lead-img"
    # Try src-first ordering
    img_match = re.search(
        r'<img[^>]*src="([^"]*)"[^>]*alt="([^"]*)"[^>]*class="lead-img"',
        html
    )
    if not img_match:
        # Try alt-first ordering
        img_match = re.search(
            r'<img[^>]*alt="([^"]*)"[^>]*src="([^"]*)"[^>]*class="lead-img"',
            html
        )
        if img_match:
            img_alt, img_src = img_match.group(1), img_match.group(2)
        else:
            img_src, img_alt = "", ""
    else:
        img_src, img_alt = img_match.group(1), img_match.group(2)

    # Article-relative img src (../images/foo.webp) -> root-relative (images/foo.webp)
    img_src = img_src.replace("../images/", "images/")

    # Article tag span
    tag_match = re.search(
        r'<span\s+class="article-tag\s+(tag-[\w-]+)"[^>]*>([^<]+)</span>',
        html
    )
    if tag_match:
        tag_class = tag_match.group(1)
        tag_label = tag_match.group(2).strip()
        # Many tags in articles use specific labels (e.g. "Decision Framework").
        # For the card listing we want the GENERIC filter-aligned label
        # ("Guide", "Safety", etc.) so cards group consistently. Derive from class.
        generic_label = {
            "tag-guide": "&#9878;&#65039; Guide",
            "tag-safety": "&#128293; Safety",
            "tag-emergency": "&#128680; Emergency",
            "tag-cost": "&#128176; Cost Guide",
            "tag-maintenance": "&#128295; Maintenance",
            "tag-seasonal": "&#127777;&#65039; Seasonal",
        }.get(tag_class, tag_label)
        tag_label = generic_label
    else:
        tag_class = "tag-guide"
        tag_label = "&#9878;&#65039; Guide"

    return {"img_src": img_src, "img_alt": img_alt, "tag_class": tag_class, "tag_label": tag_label}


def format_date_label(date_str: str) -> str:
    """2026-06-05 -> 'June 2026'"""
    try:
        y, m, _ = date_str.split("-")
        return f"{MONTHS[int(m) - 1]} {y}"
    except Exception:
        return date_str


def slug_to_url(path: str) -> str:
    """articles/foo.html -> articles/foo; article-bar.html -> article-bar"""
    return path[:-5] if path.endswith(".html") else path


def render_articles_card(a: dict) -> str:
    """Card markup matching the articles.html convention (with data-category)."""
    meta = a["_meta"]
    data_category = TAG_TO_CATEGORY.get(meta["tag_class"], "guide")
    url = slug_to_url(a["path"])
    return (
        f'                    <article class="article-card" data-category="{data_category}">\n'
        f'                        <div class="article-img-wrap"><img src="{meta["img_src"]}" alt="{meta["img_alt"]}"\n'
        f'                                loading="lazy" width="1280" height="720" /><span class="article-tag {meta["tag_class"]}">{meta["tag_label"]}</span></div>\n'
        f'                        <div class="article-body">\n'
        f'                            <div class="article-meta"><span>{format_date_label(a["date_published"])}</span></div>\n'
        f'                            <h3><a href="{url}">{a["title"]}</a></h3>\n'
        f'                            <p>{a["card_description"]}</p>\n'
        f'                            <div class="article-footer"><a href="{url}" class="read-more">Read Article &rarr;</a></div>\n'
        f'                        </div>\n'
        f'                    </article>\n\n'
    )


def render_author_card(a: dict) -> str:
    """Card markup matching the author-gyanesh.html convention (with Cn cluster prefix)."""
    meta = a["_meta"]
    short = cluster_short_id(a["cluster_id"])
    role = "pillar" if a["is_pillar"] else "cluster"
    desc = f"{short} {role} &mdash; {a['card_description']}"
    url = slug_to_url(a["path"])
    return (
        f'                    <article class="article-card">\n'
        f'                        <div class="article-img-wrap">\n'
        f'                            <img src="{meta["img_src"]}" alt="{meta["img_alt"]}" loading="lazy" width="1280" height="720" />\n'
        f'                            <span class="article-tag {meta["tag_class"]}">{meta["tag_label"]}</span>\n'
        f'                        </div>\n'
        f'                        <div class="article-body">\n'
        f'                            <div class="article-meta"><span>{format_date_label(a["date_published"])}</span></div>\n'
        f'                            <h3><a href="{url}">{a["title"]}</a></h3>\n'
        f'                            <p>{desc}</p>\n'
        f'                            <div class="article-footer"><a href="{url}" class="read-more">Read Article &rarr;</a></div>\n'
        f'                        </div>\n'
        f'                    </article>\n\n'
    )


def replace_sentinel_block(file_path: Path, start_marker: str, end_marker: str, new_content: str) -> bool:
    """Replace block between sentinels. Returns True on success, False if sentinels missing."""
    html = file_path.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(start_marker) + r".*?" + re.escape(end_marker),
        re.DOTALL
    )
    if not pattern.search(html):
        return False
    replacement = f"{start_marker}\n{new_content}                    {end_marker}"
    new_html = pattern.sub(lambda m: replacement, html, count=1)
    file_path.write_text(new_html, encoding="utf-8", newline="\n")
    return True


# ---------------------------------------------------------------------------
# Migration: extract card_description from current articles.html cards into
# cluster_map.json (one-time, runs before sentinels are added).
# ---------------------------------------------------------------------------

CARD_RE = re.compile(
    r'<article class="article-card"[^>]*>.*?'
    r'<h3>\s*<a href="([^"]+)">([^<]+)</a>\s*</h3>\s*'
    r'<p>([^<]*(?:<[^p][^>]*>[^<]*</[^>]+>[^<]*)*?)</p>\s*'
    r'<div class="article-footer">',
    re.DOTALL
)


def migrate_descriptions():
    """Extract descriptions from current articles.html cards into cluster_map.json card_description fields."""
    cmap = load_cluster_map()
    html = ARTICLES_HTML.read_text(encoding="utf-8")
    # slug -> description
    descriptions = {}
    for m in CARD_RE.finditer(html):
        url, _title, desc = m.group(1), m.group(2), m.group(3)
        # Strip articles/ prefix to get slug
        if url.startswith("articles/"):
            slug = url[len("articles/"):]
        else:
            slug = url
        descriptions[slug] = desc.strip()

    # Apply to cluster_map
    written = 0
    for cid, c in cmap["clusters"].items():
        p = c.get("pillar")
        if p and p["slug"] in descriptions:
            if p.get("card_description") != descriptions[p["slug"]]:
                p["card_description"] = descriptions[p["slug"]]
                written += 1
        for a in c.get("articles", []):
            if a["slug"] in descriptions:
                if a.get("card_description") != descriptions[a["slug"]]:
                    a["card_description"] = descriptions[a["slug"]]
                    written += 1

    save_cluster_map(cmap)
    print(f"Migration: extracted {len(descriptions)} descriptions; wrote {written} new/updated fields to cluster_map.json")

    # Report any cards in articles.html that didn't match a cluster_map slug
    cmap_slugs = set()
    for cid, c in cmap["clusters"].items():
        p = c.get("pillar")
        if p:
            cmap_slugs.add(p["slug"])
        for a in c.get("articles", []):
            cmap_slugs.add(a["slug"])
    orphans = set(descriptions.keys()) - cmap_slugs
    if orphans:
        print(f"WARN: {len(orphans)} cards in articles.html have no cluster_map entry:")
        for s in sorted(orphans):
            print(f"  - {s}")
    # And any cluster_map articles that didn't get a description
    missing = set()
    for cid, c in cmap["clusters"].items():
        p = c.get("pillar")
        if p and p.get("status") == "live" and not p.get("card_description"):
            missing.add(p["slug"])
        for a in c.get("articles", []):
            if a.get("status") == "live" and not a.get("card_description"):
                missing.add(a["slug"])
    if missing:
        print(f"WARN: {len(missing)} live cluster_map articles still have no card_description:")
        for s in sorted(missing):
            print(f"  - {s}")
    return 0


def generate():
    cmap = load_cluster_map()
    articles = collect_articles(cmap)
    # Enrich with HTML-extracted hero / tag
    for a in articles:
        a["_meta"] = parse_article_meta(ROOT / a["path"])

    # Render
    cards_articles = "".join(render_articles_card(a) for a in articles)
    cards_author = "".join(render_author_card(a) for a in articles)

    ok_a = replace_sentinel_block(ARTICLES_HTML, ARTICLES_SENTINEL_START, ARTICLES_SENTINEL_END, cards_articles)
    ok_b = replace_sentinel_block(AUTHOR_HTML, ARTICLES_SENTINEL_START, ARTICLES_SENTINEL_END, cards_author)

    if not ok_a:
        print(f"ERROR: sentinels missing in {ARTICLES_HTML.name}. Add this around the article grid:", file=sys.stderr)
        print(f"  {ARTICLES_SENTINEL_START}", file=sys.stderr)
        print(f"  ... cards ...", file=sys.stderr)
        print(f"  {ARTICLES_SENTINEL_END}", file=sys.stderr)
        return 1
    if not ok_b:
        print(f"ERROR: sentinels missing in {AUTHOR_HTML.name}. Add the same block around the .articles-grid.", file=sys.stderr)
        return 1

    print(f"Wrote {ARTICLES_HTML.name} ({len(articles)} cards) and {AUTHOR_HTML.name} ({len(articles)} cards)")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--migrate", action="store_true",
                        help="One-time backfill of card_description into cluster_map.json from current articles.html")
    parser.add_argument("--generate", action="store_true",
                        help="(Default) Generate the two grids into articles.html and author-gyanesh.html")
    args = parser.parse_args()

    if args.migrate:
        return migrate_descriptions()
    return generate()


if __name__ == "__main__":
    raise SystemExit(main())
