"""
Eliminate the "preloaded font not used within a few seconds" Chrome warning
across every page on the site, using the right tactic per page class.

Why
---
The site preloads /fonts/inter-latin.woff2 and /fonts/outfit-latin.woff2 via
<link rel="preload">, but the matching @font-face rules live in
css/style.min.css which loads after the preload. Chrome's preload heuristic
fires "preloaded but not used within a few seconds" because by the time the
@font-face is registered, the heuristic's window has expired.

Two-strategy fix
----------------
Pages WITH an inline <style> block (root pages, locations, etc. — they have
critical CSS inlined for .page-hero / .city-hero per CLAUDE.md performance
patterns):
  * Inject minimal @font-face rules at the top of the inline <style>. The
    inline CSS parses immediately, registers @font-face, and the preloaded
    woff2 matches on arrival. Preloads keep their performance benefit.

Pages WITHOUT an inline <style> block (articles — their LCP is a hero WebP,
not text):
  * Remove the font preloads entirely. On articles, preloading fonts steals
    bandwidth from the LCP hero image. font-display:swap in style.min.css
    handles the body-font swap when CSS arrives.

Idempotent. Safe to re-run.

Skipped:
  - _dist/ (build output, regenerated by build.sh)
"""

from pathlib import Path
import re


ROOT = Path(__file__).parent.parent

# Two minimal @font-face rules — latin subset only. The latin-ext rules live
# in style.min.css with their unicode-range filters and remain there.
# We omit unicode-range here so the browser uses these for any character it
# can render; for HVAC English content, latin alone covers all rendered text.
FONT_FACE_BLOCK = (
    "@font-face{font-family:'Inter';font-style:normal;font-weight:400 900;"
    "font-display:swap;src:url('/fonts/inter-latin.woff2') format('woff2')}"
    "@font-face{font-family:'Outfit';font-style:normal;font-weight:400 800;"
    "font-display:swap;src:url('/fonts/outfit-latin.woff2') format('woff2')}"
)


# Match <style>...</style> in <head>. Non-greedy so we get the FIRST one only.
STYLE_BLOCK_RE = re.compile(r"(<style[^>]*>)(.*?)(</style>)", re.DOTALL)
# Optional leading @charset directive inside the style block.
CHARSET_RE = re.compile(r'\A\s*(@charset\s+["\'][^"\']+["\'];?)\s*')

# Match a <link rel="preload" ... .woff2 ...> tag plus its trailing newline.
FONT_PRELOAD_RE = re.compile(
    r'^[ \t]*<link\s+rel=["\']preload["\'][^>]*\.woff2[^>]*>\s*\n',
    re.MULTILINE,
)


def transform(html: str) -> tuple[str, str]:
    """Return (new_html, status). status in {inlined, stripped, already, no_change}."""
    m = STYLE_BLOCK_RE.search(html)
    if m:
        # Strategy A: inline @font-face into the existing <style> block.
        open_tag, content, close_tag = m.groups()
        if "@font-face" in content[:1000]:
            return html, "already"
        cm = CHARSET_RE.match(content)
        if cm:
            charset_part = cm.group(1)
            rest = content[cm.end():]
            new_content = charset_part + FONT_FACE_BLOCK + rest
        else:
            new_content = FONT_FACE_BLOCK + content.lstrip()
        new_html = html[: m.start()] + open_tag + new_content + close_tag + html[m.end():]
        return new_html, "inlined"
    # Strategy B: no inline style → remove font preloads (article pattern).
    new_html, n = FONT_PRELOAD_RE.subn("", html)
    if n > 0:
        return new_html, "stripped"
    return html, "no_change"


def html_files() -> list[Path]:
    """Every HTML file in the working tree, excluding build output and drafts."""
    files: list[Path] = []
    for f in ROOT.glob("*.html"):
        files.append(f)
    for f in (ROOT / "articles").glob("*.html"):
        files.append(f)
    for f in (ROOT / "locations").glob("*.html"):
        files.append(f)
    return sorted(files)


def main() -> int:
    files = html_files()
    counts = {"inlined": 0, "stripped": 0, "already": 0, "no_change": 0}
    for f in files:
        original = f.read_text(encoding="utf-8")
        new_html, status = transform(original)
        counts[status] += 1
        if status in ("inlined", "stripped"):
            f.write_text(new_html, encoding="utf-8", newline="\n")
    total = sum(counts.values())
    print(f"Total HTML files scanned: {total}")
    print(f"  inlined @font-face:  {counts['inlined']}")
    print(f"  stripped preloads:   {counts['stripped']}")
    print(f"  already done:        {counts['already']}")
    print(f"  no change needed:    {counts['no_change']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
