"""
Regenerate the _redirects file to cover every TRACKED .html file in the repo.

Why it exists
-------------
_redirects was hand-written on 2026-04-08 and drifted: new pages added
after that date had no explicit 301 entry. Cloudflare Pages auto-redirects
those with a 308 as a fallback, so it wasn't broken -- but explicit 301s
are better hygiene: 301 is more universally recognized by every crawler,
and having every page's redirect in source means fewer surprises if
Cloudflare's routing behavior ever changes.

Source of truth: git-tracked .html files (via `git ls-files`). Using the
tracked set (not a filesystem glob) means untracked scratch / draft / WIP
HTML in the working tree doesn't bleed into _redirects — only files that
actually deploy get redirects.

Auto-invoked from:
  - build.sh (Cloudflare Pages deploy-time backstop — Layer 1)
  - scripts/pre-commit (commit-time sync — Layer 2, only when HTML A/D/R)

Run manually if you want to preview the regen output. Idempotent.
"""

import subprocess
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT = ROOT / "_redirects"

HEADER = (
    "# 301 redirects: .html URLs -> clean URLs (SEO canonicalization)\n"
    "# Auto-generated by scripts/regenerate_redirects.py -- do not hand-edit.\n"
    "# Regenerated automatically by build.sh on every deploy + by the pre-commit hook.\n\n"
)


def tracked_html() -> list[str]:
    """All .html files git is tracking, repo-relative. Falls back to glob if not in git."""
    try:
        result = subprocess.run(
            ["git", "ls-files", "*.html"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
        files = [line.strip() for line in result.stdout.splitlines() if line.strip()]
        if files:
            return files
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass
    # Fallback: filesystem glob (used only outside git contexts — e.g. a tarball release)
    fs_files: list[str] = []
    for f in ROOT.glob("*.html"):
        fs_files.append(f.name)
    for f in (ROOT / "locations").glob("*.html"):
        fs_files.append(f"locations/{f.name}")
    for f in (ROOT / "articles").glob("*.html"):
        fs_files.append(f"articles/{f.name}")
    return fs_files


def collect_paths() -> list[str]:
    """Return sorted list of /path (no .html) strings for every servable HTML file."""
    paths = []
    for rel in tracked_html():
        # Mirror build.sh allowlist: index.html serves at /, 404.html is the fallback.
        # Neither needs a .html -> clean redirect.
        if rel in ("index.html", "404.html"):
            continue
        paths.append("/" + rel[:-5])  # strip .html
    return sorted(paths)


def main() -> int:
    paths = collect_paths()
    lines = [HEADER]
    for p in paths:
        lines.append(f"{p}.html {p} 301\n")
    OUT.write_text("".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {OUT} with {len(paths)} 301 entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
