"""
Regenerate the _redirects file to cover EVERY .html file on disk.

Why it exists
-------------
_redirects was hand-written on 2026-04-08 and drifted: new pages added
after that date (32 new location files + image-credits.html) had no
explicit 301 entry. Cloudflare Pages auto-redirects those with a 308
as a fallback, so it wasn't broken -- but explicit 301s are better
hygiene: 301 is more universally recognized by every crawler, and
having every page's redirect in source means fewer surprises if
Cloudflare's routing behavior ever changes.

This script walks the repo's HTML files and emits a redirect line
per file, so it's impossible for _redirects to drift behind the
actual page set.

Run after:
  - Adding any new root-level .html page
  - Adding any new locations/*.html page
  - Adding any new articles/*.html page

Idempotent. Output is stable sorted. Safe to re-run.
"""

from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT = ROOT / "_redirects"

# Header (preserves the original file's intent comment)
HEADER = (
    "# 301 redirects: .html URLs -> clean URLs (SEO canonicalization)\n"
    "# Auto-generated by scripts/regenerate_redirects.py -- do not hand-edit.\n"
    "# Re-run after adding new HTML pages anywhere in the site.\n\n"
)


def collect_paths() -> list[str]:
    """Return sorted list of /path (no .html) strings for every servable HTML file."""
    paths = []
    # Root-level .html (exclude index.html and 404.html)
    for f in (ROOT).glob("*.html"):
        name = f.name
        if name in ("index.html", "404.html"):
            continue
        paths.append("/" + name[:-5])  # strip .html
    # locations/*.html
    for f in (ROOT / "locations").glob("*.html"):
        paths.append("/locations/" + f.name[:-5])
    # articles/*.html
    for f in (ROOT / "articles").glob("*.html"):
        paths.append("/articles/" + f.name[:-5])
    return sorted(paths)


def main() -> int:
    paths = collect_paths()
    lines = [HEADER]
    for p in paths:
        lines.append(f"{p}.html {p} 301\n")
    OUT.write_text("".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {OUT} with {len(paths)} 301 entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
